<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>1920279f-3a0f-45df-b14c-b253c6ae86a0</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Identity\FiapCloudGames.Identity.Presentation\FiapCloudGames.Identity.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\FiapCloudGames.Identity.Infrastructure\FiapCloudGames.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\FiapCloudGames.Catalog.Presentation\FiapCloudGames.Catalog.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\FiapCloudGames.Catalog.Infrastructure\FiapCloudGames.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Library\FiapCloudGames.Library.Presentation\FiapCloudGames.Library.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Library\FiapCloudGames.Library.Infrastructure\FiapCloudGames.Library.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Promotions\FiapCloudGames.Promotions.Presentation\FiapCloudGames.Promotions.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Promotions\FiapCloudGames.Promotions.Infrastructure\FiapCloudGames.Promotions.Infrastructure.csproj" />
  </ItemGroup>
</Project>
