<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FiapCloudGames.Presentation.Common\FiapCloudGames.Presentation.Common.csproj" />
    <ProjectReference Include="..\FiapCloudGames.Identity.Application\FiapCloudGames.Identity.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
