FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore src/Database/FiapCloudGames.Database.Migrations/FiapCloudGames.Database.Migrations.csproj
RUN dotnet publish src/Database/FiapCloudGames.Database.Migrations/FiapCloudGames.Database.Migrations.csproj -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app
COPY --from=build /app .
USER $APP_UID
ENTRYPOINT ["dotnet", "FiapCloudGames.Database.Migrations.dll"]
