<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>032e4e86-8c4d-4fb2-87b5-e022b0998880</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Catalog\FiapCloudGames.Catalog.Infrastructure\FiapCloudGames.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\FiapCloudGames.Identity.Infrastructure\FiapCloudGames.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Library\FiapCloudGames.Library.Infrastructure\FiapCloudGames.Library.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Promotions\FiapCloudGames.Promotions.Infrastructure\FiapCloudGames.Promotions.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\Identity\" />
    <Folder Include="Migrations\Catalog\" />
    <Folder Include="Migrations\Library\" />
    <Folder Include="Migrations\Promotions\" />
  </ItemGroup>

</Project>